import pyautogui as pag
import time
 
pag.PAUSE = 0.3
pag.press("win")
pag.write("chrome")
pag.press("enter")
pag.click(x=1339, y=1044)
pag.write("Seu computador - Boa noite, Sarah! Como voce esta?")
pag.press("enter")
pag.press("enter")
pag.write("Seu computador - Nao tenha medo, eu sou o seu computador.")
pag.press("enter")
pag.press("enter")
pag.write("Seu computador - So queria te passar uma mensagem que o computador do seu amor me passou para voce...")
pag.press("enter")
pag.write("Seu computador - A mensagem foi a seguinte:")
pag.press("enter")
pag.press("enter")
pag.write("Computador do seu amor - Ola, Sarah!")
pag.press("enter")
pag.write("Computador do seu amor - A mensagem do Jao (meu mestre) foi:")
pag.press("enter")
pag.press("enter")
pag.write("Jao - Sarah, eu te amo!")
pag.press("enter")
pag.write("Jao - I love you!")
pag.press("enter")
pag.write("Jao - Jeg elsker deg!")
pag.press("enter")
pag.write("Jao - Kocham cię!")
pag.press("enter")
pag.write("Jao - Is breá liom tú!")
pag.press("enter")
pag.write("Jao - mujhe tumase pyaar hai!")
pag.press("enter")
pag.press("enter")
pag.write("Computador do seu amor - E foi isto que o Jao me pediu para te dizer. Ate mais!")
pag.press("enter")
pag.press("enter")
pag.write("Seu computador - A mensagem foi entregue, ate uma proxima vez. Minha mestra!")

time.sleep(5)